# Generated by Django 3.1.7 on 2021-04-05 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Silhouette_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('pic_dir', models.CharField(max_length=100)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.kid')),
            ],
        ),
        migrations.CreateModel(
            name='Silhouette_character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_eng_name', models.CharField(max_length=50)),
                ('character_kor_name', models.CharField(max_length=50)),
                ('character_jpn_name', models.CharField(max_length=50)),
                ('character_chn_name', models.CharField(max_length=50)),
                ('open_pic_dir', models.CharField(max_length=128)),
                ('close_pic_dir', models.CharField(max_length=128)),
                ('checked', models.BooleanField(default=False)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.kid')),
                ('silhouette_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silhouettes.silhouette_book')),
            ],
        ),
    ]
